version: "3"

services:
  db:
    image: docker.uclv.cu/mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
#    env_file: ./env/mongo/.env